name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install and lint
        run: |
          npm install
          npm run eslint
  test:
    name: Test with Jest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run test-coverage
      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v1
